version: "3.6"
networks:
    local_foo-system:
        external: true
services:
    
    service3:
        build: .
        image: "service3"

    service3-run:
        image: "nginx:1.17-alpine"
        stdin_open: true
        tty: true
        networks:
            - local_foo-system
        volumes:
            - ./src/:/usr/share/nginx/html
            - ./nginx.conf:/etc/nginx/nginx.conf
        command: ["nginx" , "-g", "daemon off;"]