version: "3.7"
services:
  go-project:
    build: .

  go-project-dev:
    image: "golang:1.12"
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - ./.go:/go
    command: ["sh", "-c", "/app/_scripts/dev.sh"]
