version: "3.7"
services:
  ui-lib:
    image: "ui-lib"
    build: .
  
  ui-lib-run:
    image: "node:13.10"
    stdin_open: true
    tty: true
    working_dir: "/app"
    volumes: 
        - ./:/app
    ports: 
        - 6006:6006
    command: ["sh", "-c", "yarn install && yarn start"]

  ui-lib-dev:
    image: "node:13.10"
    stdin_open: true
    tty: true
    working_dir: "/app"
    volumes: 
        - ./:/app
    ports: 
        - 6006:6006
    environment: 
      - PUPPETEER_URL=http://host.docker.internal:9922
      - CI=false
    command: ["sh", "-c", "yarn install && yarn tdd"]

  ui-lib-test:
    build:
      context: .
      dockerfile: "test.Dockerfile"
    depends_on:
      - ui-lib
    stdin_open: true
    tty: true
    working_dir: "/app"
    volumes: 
        - ./:/app
    ports: 
        - 9922:9922
    command: ["sh", "-c", "yarn install && yarn test"]
